/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as DealershipRouteImport } from './routes/dealership'
import { Route as EnginePartsRouteImport } from './routes/engine-parts'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as OemAuditRouteImport } from './routes/oem-audit'
import { Route as PaintsRouteImport } from './routes/paints'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as TuneLabRouteImport } from './routes/tune-lab'
import { Route as TuningWorkbenchRouteImport } from './routes/tuning-workbench'
import { Route as UnlocksRouteImport } from './routes/unlocks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const DealershipRoute = DealershipRouteImport.update({
  id: '/dealership',
  path: '/dealership',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginePartsRoute = EnginePartsRouteImport.update({
  id: '/engine-parts',
  path: '/engine-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const OemAuditRoute = OemAuditRouteImport.update({
  id: '/oem-audit',
  path: '/oem-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintsRoute = PaintsRouteImport.update({
  id: '/paints',
  path: '/paints',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const TuneLabRoute = TuneLabRouteImport.update({
  id: '/tune-lab',
  path: '/tune-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const TuningWorkbenchRoute = TuningWorkbenchRouteImport.update({
  id: '/tuning-workbench',
  path: '/tuning-workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlocksRoute = UnlocksRouteImport.update({
  id: '/unlocks',
  path: '/unlocks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/cars': typeof CarsRoute
  '/challenges': typeof ChallengesRoute
  '/dealership': typeof DealershipRoute
  '/engine-parts': typeof EnginePartsRoute
  '/engines': typeof EnginesRoute
  '/oem-audit': typeof OemAuditRoute
  '/paints': typeof PaintsRoute
  '/parts': typeof PartsRoute
  '/tune-lab': typeof TuneLabRoute
  '/tuning-workbench': typeof TuningWorkbenchRoute
  '/unlocks': typeof UnlocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/cars': typeof CarsRoute
  '/challenges': typeof ChallengesRoute
  '/dealership': typeof DealershipRoute
  '/engine-parts': typeof EnginePartsRoute
  '/engines': typeof EnginesRoute
  '/oem-audit': typeof OemAuditRoute
  '/paints': typeof PaintsRoute
  '/parts': typeof PartsRoute
  '/tune-lab': typeof TuneLabRoute
  '/tuning-workbench': typeof TuningWorkbenchRoute
  '/unlocks': typeof UnlocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/cars': typeof CarsRoute
  '/challenges': typeof ChallengesRoute
  '/dealership': typeof DealershipRoute
  '/engine-parts': typeof EnginePartsRoute
  '/engines': typeof EnginesRoute
  '/oem-audit': typeof OemAuditRoute
  '/paints': typeof PaintsRoute
  '/parts': typeof PartsRoute
  '/tune-lab': typeof TuneLabRoute
  '/tuning-workbench': typeof TuningWorkbenchRoute
  '/unlocks': typeof UnlocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/cars'
    | '/challenges'
    | '/dealership'
    | '/engine-parts'
    | '/engines'
    | '/oem-audit'
    | '/paints'
    | '/parts'
    | '/tune-lab'
    | '/tuning-workbench'
    | '/unlocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/cars'
    | '/challenges'
    | '/dealership'
    | '/engine-parts'
    | '/engines'
    | '/oem-audit'
    | '/paints'
    | '/parts'
    | '/tune-lab'
    | '/tuning-workbench'
    | '/unlocks'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/cars'
    | '/challenges'
    | '/dealership'
    | '/engine-parts'
    | '/engines'
    | '/oem-audit'
    | '/paints'
    | '/parts'
    | '/tune-lab'
    | '/tuning-workbench'
    | '/unlocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CarsRoute: typeof CarsRoute
  ChallengesRoute: typeof ChallengesRoute
  DealershipRoute: typeof DealershipRoute
  EnginePartsRoute: typeof EnginePartsRoute
  EnginesRoute: typeof EnginesRoute
  OemAuditRoute: typeof OemAuditRoute
  PaintsRoute: typeof PaintsRoute
  PartsRoute: typeof PartsRoute
  TuneLabRoute: typeof TuneLabRoute
  TuningWorkbenchRoute: typeof TuningWorkbenchRoute
  UnlocksRoute: typeof UnlocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealership': {
      id: '/dealership'
      path: '/dealership'
      fullPath: '/dealership'
      preLoaderRoute: typeof DealershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-parts': {
      id: '/engine-parts'
      path: '/engine-parts'
      fullPath: '/engine-parts'
      preLoaderRoute: typeof EnginePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oem-audit': {
      id: '/oem-audit'
      path: '/oem-audit'
      fullPath: '/oem-audit'
      preLoaderRoute: typeof OemAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paints': {
      id: '/paints'
      path: '/paints'
      fullPath: '/paints'
      preLoaderRoute: typeof PaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tune-lab': {
      id: '/tune-lab'
      path: '/tune-lab'
      fullPath: '/tune-lab'
      preLoaderRoute: typeof TuneLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning-workbench': {
      id: '/tuning-workbench'
      path: '/tuning-workbench'
      fullPath: '/tuning-workbench'
      preLoaderRoute: typeof TuningWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlocks': {
      id: '/unlocks'
      path: '/unlocks'
      fullPath: '/unlocks'
      preLoaderRoute: typeof UnlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CarsRoute: CarsRoute,
  ChallengesRoute: ChallengesRoute,
  DealershipRoute: DealershipRoute,
  EnginePartsRoute: EnginePartsRoute,
  EnginesRoute: EnginesRoute,
  OemAuditRoute: OemAuditRoute,
  PaintsRoute: PaintsRoute,
  PartsRoute: PartsRoute,
  TuneLabRoute: TuneLabRoute,
  TuningWorkbenchRoute: TuningWorkbenchRoute,
  UnlocksRoute: UnlocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
